name: Update Live Streams

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:       # Allows manual triggering

jobs:
  update_live_streams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install google-api-python-client PyGithub

      - name: Run the script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}  # Use GitHub Secrets
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub Secrets
        run: python Youtube.py
