name: Update Live Streams

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at the start of the hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-live-streams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install google-api-python-client PyGithub

      - name: Run Script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}  # Correct secret name
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}   # Correct secret name
        run: python Youtube.py
